spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/prac-search-demo?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 12345678
  data:
    mongodb:
      database: prac-search-demo-history
      host: your host
      port: 27017

server:
  port: 9999
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.juzi.search.pojo

